In [3]:
import numpy as np

In [6]:
tmp_ararry_1 = np.array([1,2,3])
print('tmp_array_1 type: ', type(tmp_ararry_1))
print('tmp_array_1 shape: ', tmp_ararry_1.shape)

tmp_ararry_2 = np.array([[1,2,3],
                        [4,5,6]])
print('tmp_array_1 type: ', type(tmp_ararry_2))
print('tmp_array_1 shape: ', tmp_ararry_2.shape)

tmp_ararry_3 = np.array([[1,2,3],
                         [4,5,6],
                         [7,8,9]])
print('tmp_array_1 type: ', type(tmp_ararry_3))
print('tmp_array_1 shape: ', tmp_ararry_3.shape)

tmp_ararry_4 = np.array([[1,2,3]])
print('tmp_array_1 type: ', type(tmp_ararry_4))
print('tmp_array_1 shape: ', tmp_ararry_4.shape)

tmp_array_1 type:  <class 'numpy.ndarray'>
tmp_array_1 shape:  (3,)
tmp_array_1 type:  <class 'numpy.ndarray'>
tmp_array_1 shape:  (2, 3)
tmp_array_1 type:  <class 'numpy.ndarray'>
tmp_array_1 shape:  (3, 3)
tmp_array_1 type:  <class 'numpy.ndarray'>
tmp_array_1 shape:  (1, 3)


In [7]:
print("tmp_array_1's dimension: ", format(tmp_ararry_1.ndim) )

tmp_array_1's dimension:  1


In [8]:
list = [1,2,3]
print(type(list))

array1 = np.array(list)
print(type(array1))
print(array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
int32


In [12]:
#arange를 통해 연속적인 숫자의 nparray를 만들 수 있다.
ar_array = np.arange(10)
print(ar_array)
print(ar_array.shape, ar_array.dtype)

#start와 stop으로 시작과 끝을 정해줄 수 있다.
ar_array1 = np.arange(start = 1, stop = 10)
print(ar_array1)
print(ar_array1.shape, ar_array1.dtype)

[0 1 2 3 4 5 6 7 8 9]
(10,) int32
[1 2 3 4 5 6 7 8 9]
(9,) int32


In [16]:
#"zeros"를 사용하여 모든 값을 0으로 채운 nparray를 만들 수 있다.
z_array = np.zeros((3,2), dtype = 'int32')
print(z_array)
print(z_array.dtype, z_array.shape)

print()
#'ones'도 zoers와 비슷하게 1로 모든 값을 채운 nparray를 준다.
o_array = np.ones((3,2))
print(o_array)
print(o_array.dtype, o_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [20]:
array1 = np.arange(10)
print(array1,"\n")

array2 = array1.reshape(2,5)
print(array2,"\n")

array3 = array1.reshape(5,2)
print(array3,"\n")

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 



In [21]:
#10은 3으로 나눠지지 않으므로 에러가 난다.
array1.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [25]:
array1 = np.arange(10)

array2 = array1.reshape(-1,5)
print(array2, "\n")

array3 = array1.reshape(5,-1)
print(array3)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [33]:
array1 = np.arange(8)

array2 = array1.reshape(2,2,2)
print(array2.dtype ,",", array2, "\n")

#tolist()를 통해 데이터 타입을 list로 변경할 수 있다.
array3 = array2.tolist()
print(array3)

int32 , [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [11]:
array1 = np.arange(start=1, stop=10)
print(array1)

#1번째 부터 3번째까지
array2 = array1[0:3]
print(array2)

array3 = array1[0:]
print(array3)

array4 = array1[:]
print(array4)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [17]:
array1 = np.arange(start = 1, stop = 10)
print(array1)

#boolean indexing 가능
bo_array = array1 > 5

print(bo_array)
print(bo_array.dtype)

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
bool


In [22]:
boolean_index = np.array(bo_array.tolist())

print(boolean_index)

#boolean리스트를 통해 True인 값만 반환 가능
array3 = array1[boolean_index]
print(array3)

[False False False False False  True  True  True  True]
[6 7 8 9]


In [32]:
#sort()

unsorted_array = np.array([5,2,7,3,1])
print(unsorted_array)

#반환해주는 형식
np.sort(unsorted_array)
print(unsorted_array)

sorted_array = np.sort(unsorted_array)
print(sorted_array)

#반환해주지않고 원본 배열이 바뀜
sorted_array2 = unsorted_array.sort()
print(sorted_array2)

print(unsorted_array)

[5 2 7 3 1]
[5 2 7 3 1]
[1 2 3 5 7]
None
[1 2 3 5 7]


In [34]:
#내림차순도 가능하다.
unsorted_array = np.array([5,2,7,3,1])

des_sorted_array = np.sort(unsorted_array)[::-1]
print(des_sorted_array)

[7 5 3 2 1]


In [40]:
array1 = np.array([[8,5],
                  [6,4]])
print(array1, "\n")

#row방향 정렬
print(np.sort(array1, axis = 0), "\n")

#column방향 정렬
print(np.sort(array1, axis = 1), "\n")

[[8 5]
 [6 4]] 

[[6 4]
 [8 5]] 

[[5 8]
 [4 6]] 



In [42]:
#argsort()

array1 = np.array([3,1,5,2])

so_idx = np.argsort(array1)
print(so_idx)

so_idx = np.argsort(array1)[::-1]
print(so_idx)

[1 3 0 2]
[2 0 3 1]


In [48]:
#행렬 곱
array1 = np.array([[1,2,3],
                   [4,5,6]])

array2 = np.array([[7,8],
                   [9,10],
                   [11,12]])

array3 = np.dot(array1, array2)
print(array3, "\n")

#transpose
array4 = np.transpose(array1)
print(array4, "\n")

array5 = np.transpose(array2)
print(array5)

[[ 58  64]
 [139 154]] 

[[1 4]
 [2 5]
 [3 6]] 

[[ 7  9 11]
 [ 8 10 12]]
